EntityBundle\Entity\Person:
    type: entity
    table: null
    oneToMany:
        attendances:
            targetEntity: Attendance
            mappedBy: person
          
        transactions:
            targetEntity: Transaction
            mappedBy: person
    
    manyToMany:
        sup:
            targetEntity: Person
            mappedBy: sub
        sub:
            targetEntity: Person
            inversedBy: sup
            joinTable:
                name: hierarchy
                joinColumns:
                    sup_id: 
                        referencedColumnName: id
                inverseJoinColumns:
                    sub_id:
                        referencedColumnName: id
    repositoryClass: EntityBundle\Repository\PersonRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        personId:
            type: integer
            unique: true
        name:
            type: string
            length: '100'
        firstname:
            type: string
            length: '100'
        mail:
            type: string
            length: '150'
            unique: true
        cin:
            type: string
            length: '20'
            unique: true
        personType:
            type: string
            length: '30'
        isActive:
            type: integer
        password:
            type: string
            length: '50'
    lifecycleCallbacks: {  }
